### ISSUE TITLE
Webpack 5 __webpack_require__ error

### ISSUE THREAD

**Issue by Neverland** [felixmariotto/three-mesh-ui#252]
app.js:5918 
        
       Uncaught TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at __webpack_require__.r (app.js:5918:21)
    at eval (three-mesh-ui.module.js:1:21)
    at ./node_modules/three-mesh-ui/build/three-mesh-ui.module.js (chunk-vendors.js:8733:1)
    at __webpack_require__ (app.js:5709:33)
    at fn (app.js:5987:21)
    at eval (createLabel.js:5:71)
    at ./src/system_4dlabel/errorMarker/createLabel.js (app.js:2065:1)
    at __webpack_require__ (app.js:5709:33)
    at fn (app.js:5987:21)

**Comment by Neverland** [comment]
config.resolve.alias
            .set(
                'three-mesh-ui',
                resolve('node_modules/three-mesh-ui/build/three-mesh-ui.module.min.js')
            );
